# CMake generated Testfile for 
# Source directory: /workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/traffic-control
# Build directory: /workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/cmake-cache/examples/traffic-control
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-traffic-control "ns3.40-traffic-control-debug")
set_tests_properties(ctest-traffic-control PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/traffic-control/CMakeLists.txt;1;build_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-queue-discs-benchmark "ns3.40-queue-discs-benchmark-debug")
set_tests_properties(ctest-queue-discs-benchmark PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/traffic-control/CMakeLists.txt;12;build_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-red-vs-fengadaptive "ns3.40-red-vs-fengadaptive-debug")
set_tests_properties(ctest-red-vs-fengadaptive PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/traffic-control/CMakeLists.txt;24;build_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-red-vs-nlred "ns3.40-red-vs-nlred-debug")
set_tests_properties(ctest-red-vs-nlred PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/traffic-control/CMakeLists.txt;35;build_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-tbf-example "ns3.40-tbf-example-debug")
set_tests_properties(ctest-tbf-example PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/traffic-control/CMakeLists.txt;46;build_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-cobalt-vs-codel "ns3.40-cobalt-vs-codel-debug")
set_tests_properties(ctest-cobalt-vs-codel PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/traffic-control/CMakeLists.txt;56;build_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/traffic-control/CMakeLists.txt;0;")
