# CMake generated Testfile for 
# Source directory: /workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/tap-bridge/examples
# Build directory: /workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/cmake-cache/src/tap-bridge/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-tap-csma "ns3.40-tap-csma-debug")
set_tests_properties(ctest-tap-csma PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/tap-bridge/examples/CMakeLists.txt;2;build_lib_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-csma-virtual-machine "ns3.40-tap-csma-virtual-machine-debug")
set_tests_properties(ctest-tap-csma-virtual-machine PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/tap-bridge/examples/CMakeLists.txt;12;build_lib_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-wifi-virtual-machine "ns3.40-tap-wifi-virtual-machine-debug")
set_tests_properties(ctest-tap-wifi-virtual-machine PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/tap-bridge/examples/CMakeLists.txt;21;build_lib_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-wifi-dumbbell "ns3.40-tap-wifi-dumbbell-debug")
set_tests_properties(ctest-tap-wifi-dumbbell PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/tap-bridge/examples/CMakeLists.txt;32;build_lib_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/tap-bridge/examples/CMakeLists.txt;0;")
