# CMake generated Testfile for 
# Source directory: /workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src
# Build directory: /workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/cmake-cache/src
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("antenna")
subdirs("aodv")
subdirs("applications")
subdirs("bridge")
subdirs("brite")
subdirs("buildings")
subdirs("click")
subdirs("config-store")
subdirs("core")
subdirs("csma")
subdirs("csma-layout")
subdirs("dsdv")
subdirs("dsr")
subdirs("energy")
subdirs("fd-net-device")
subdirs("flow-monitor")
subdirs("internet")
subdirs("internet-apps")
subdirs("lr-wpan")
subdirs("lte")
subdirs("mesh")
subdirs("mobility")
subdirs("netanim")
subdirs("network")
subdirs("nix-vector-routing")
subdirs("olsr")
subdirs("openflow")
subdirs("point-to-point")
subdirs("point-to-point-layout")
subdirs("propagation")
subdirs("sixlowpan")
subdirs("spectrum")
subdirs("stats")
subdirs("tap-bridge")
subdirs("test")
subdirs("topology-read")
subdirs("traffic-control")
subdirs("uan")
subdirs("virtual-net-device")
subdirs("wifi")
subdirs("wimax")
