# CMake generated Testfile for 
# Source directory: /workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/wimax/examples
# Build directory: /workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/cmake-cache/src/wimax/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-wimax-ipv4 "ns3.40-wimax-ipv4-debug")
set_tests_properties(ctest-wimax-ipv4 PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/src/wimax/examples/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/wimax/examples/CMakeLists.txt;1;build_lib_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/wimax/examples/CMakeLists.txt;0;")
add_test(ctest-wimax-multicast "ns3.40-wimax-multicast-debug")
set_tests_properties(ctest-wimax-multicast PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/src/wimax/examples/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/wimax/examples/CMakeLists.txt;12;build_lib_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/wimax/examples/CMakeLists.txt;0;")
add_test(ctest-wimax-simple "ns3.40-wimax-simple-debug")
set_tests_properties(ctest-wimax-simple PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/src/wimax/examples/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/wimax/examples/CMakeLists.txt;22;build_lib_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/wimax/examples/CMakeLists.txt;0;")
