# CMake generated Testfile for 
# Source directory: /workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/tutorial
# Build directory: /workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/cmake-cache/examples/tutorial
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-hello-simulator "ns3.40-hello-simulator-debug")
set_tests_properties(ctest-hello-simulator PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/examples/tutorial/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/tutorial/CMakeLists.txt;1;build_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-first "ns3.40-first-debug")
set_tests_properties(ctest-first PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/examples/tutorial/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/tutorial/CMakeLists.txt;7;build_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-second "ns3.40-second-debug")
set_tests_properties(ctest-second PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/examples/tutorial/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/tutorial/CMakeLists.txt;17;build_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-third "ns3.40-third-debug")
set_tests_properties(ctest-third PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/examples/tutorial/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/tutorial/CMakeLists.txt;28;build_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-fourth "ns3.40-fourth-debug")
set_tests_properties(ctest-fourth PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/examples/tutorial/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/tutorial/CMakeLists.txt;40;build_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-fifth "ns3.40-fifth-debug")
set_tests_properties(ctest-fifth PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/examples/tutorial/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/tutorial/CMakeLists.txt;46;build_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-sixth "ns3.40-sixth-debug")
set_tests_properties(ctest-sixth PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/examples/tutorial/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/tutorial/CMakeLists.txt;57;build_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-seventh "ns3.40-seventh-debug")
set_tests_properties(ctest-seventh PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/examples/tutorial/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/tutorial/CMakeLists.txt;68;build_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/examples/tutorial/CMakeLists.txt;0;")
