# CMake generated Testfile for 
# Source directory: /workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/stats/examples
# Build directory: /workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/cmake-cache/src/stats/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-time-probe-example "ns3.40-time-probe-example-debug")
set_tests_properties(ctest-time-probe-example PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/src/stats/examples/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;1;build_lib_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-example "ns3.40-gnuplot-example-debug")
set_tests_properties(ctest-gnuplot-example PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/src/stats/examples/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;20;build_lib_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-double-probe-example "ns3.40-double-probe-example-debug")
set_tests_properties(ctest-double-probe-example PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/src/stats/examples/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;20;build_lib_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-aggregator-example "ns3.40-gnuplot-aggregator-example-debug")
set_tests_properties(ctest-gnuplot-aggregator-example PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/src/stats/examples/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;20;build_lib_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-helper-example "ns3.40-gnuplot-helper-example-debug")
set_tests_properties(ctest-gnuplot-helper-example PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/src/stats/examples/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;20;build_lib_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-file-aggregator-example "ns3.40-file-aggregator-example-debug")
set_tests_properties(ctest-file-aggregator-example PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/src/stats/examples/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;20;build_lib_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-file-helper-example "ns3.40-file-helper-example-debug")
set_tests_properties(ctest-file-helper-example PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/src/stats/examples/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;20;build_lib_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;0;")
