# CMake generated Testfile for 
# Source directory: /workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/internet-apps/examples
# Build directory: /workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/cmake-cache/src/internet-apps/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-dhcp-example "ns3.40-dhcp-example-debug")
set_tests_properties(ctest-dhcp-example PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/src/internet-apps/examples/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/internet-apps/examples/CMakeLists.txt;1;build_lib_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/internet-apps/examples/CMakeLists.txt;0;")
add_test(ctest-traceroute-example "ns3.40-traceroute-example-debug")
set_tests_properties(ctest-traceroute-example PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/src/internet-apps/examples/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/internet-apps/examples/CMakeLists.txt;12;build_lib_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/internet-apps/examples/CMakeLists.txt;0;")
add_test(ctest-ping-example "ns3.40-ping-example-debug")
set_tests_properties(ctest-ping-example PROPERTIES  WORKING_DIRECTORY "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build/src/internet-apps/examples/" _BACKTRACE_TRIPLES "/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/internet-apps/examples/CMakeLists.txt;25;build_lib_example;/workspaces/NS3-AlgorithmAnalysis/ns-allinone-3.40/ns-3.40/src/internet-apps/examples/CMakeLists.txt;0;")
